name: 's3 bucket creation'
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform template1'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Initialize
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.paul_works_aws}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.paul_works_aws1234 }}
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.paul_works_aws }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.paul_works_aws1234 }}
      run: terraform plan

    - name: Terraform destroy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.paul_works_aws }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.paul_works_aws1234 }}
      run: terraform destroy -auto-approve